version: '3.1'
services:
  rabbitmq:
    image: "rabbitmq:3.8.6-management"
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
  redis:
    image: redis:latest
    ports:
      - "6379:6379"